### ISSUE TITLE
Collapse instructions for adding signature to Gmail

### ISSUE THREAD

**Issue by merchako** [silinternational/email-signature-generator#25]
Current:

> 1. CLICK HERE to copy the generated signature above
> 2. Open Gmail
> 3. In the top right, click Settings
> 4. In the "Signature" section, paste in the box.
> 5. At the bottom of the page, click Save Changes.

Future:

> 1. COPY the signature
> 2. Open [Gmail settings](https://mail.google.com/mail/u/#settings/general)
> 4. Paste into the "Signature" section.
> 5. _Save Changes_ at the bottom.

**Comment by devon-sil** [comment]
Closing.  We'll be decommisioning this.
